version: '3'
services:
    lapras-api:
        user: "1001"
        container_name: lapras-api
        build:
            context: .
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        environment:
            - DB_HOST=lapras-db
        networks:
            - sail
        depends_on:
            - lapras-db

    lapras-db:
        container_name: lapras-db
        image: 'mysql/mysql-server:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - sail
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
networks:
    sail:
        external: true
